spring.application.name=taskmanager
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=admin
spring.datasource.password=adminpass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
